// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SkillManagement.API.Data.Repositories;

namespace SkillManagement.API.Data.Migrations
{
    [DbContext(typeof(SkillContext))]
    partial class SkillContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SkillManagement.API.Core.Models.Level", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasMaxLength(100);

                    b.Property<string>("LevelName")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.ToTable("Levels");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Description = "Low",
                            LevelName = "1"
                        },
                        new
                        {
                            Id = 2L,
                            Description = "Medium",
                            LevelName = "2"
                        });
                });

            modelBuilder.Entity("SkillManagement.API.Core.Models.Skill", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasMaxLength(100);

                    b.Property<string>("SkillName")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.ToTable("Skills");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Description = ".Net",
                            SkillName = ".Net core"
                        },
                        new
                        {
                            Id = 2L,
                            Description = ".Net",
                            SkillName = "Asp.Net core"
                        });
                });

            modelBuilder.Entity("SkillManagement.API.Core.Models.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("EmailId")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("LastName")
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            EmailId = "JDove@gmail.com",
                            FirstName = "John",
                            LastName = "Dove"
                        },
                        new
                        {
                            Id = 2L,
                            EmailId = "J1Dove1@gmail.com",
                            FirstName = "John1",
                            LastName = "Dove1"
                        });
                });

            modelBuilder.Entity("SkillManagement.API.Core.Models.UserSkillLevel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("LevelId");

                    b.Property<long>("SkillId");

                    b.Property<long>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("LevelId");

                    b.HasIndex("SkillId");

                    b.HasIndex("UserId");

                    b.ToTable("UserSkillLevel");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            LevelId = 1L,
                            SkillId = 1L,
                            UserId = 1L
                        },
                        new
                        {
                            Id = 2L,
                            LevelId = 2L,
                            SkillId = 2L,
                            UserId = 1L
                        });
                });

            modelBuilder.Entity("SkillManagement.API.Core.Models.UserSkillLevel", b =>
                {
                    b.HasOne("SkillManagement.API.Core.Models.Level", "Level")
                        .WithMany("UserSkillLevel")
                        .HasForeignKey("LevelId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SkillManagement.API.Core.Models.Skill", "Skill")
                        .WithMany("UserSkillLevel")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SkillManagement.API.Core.Models.User", "User")
                        .WithMany("UserSkillLevel")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
